In [5]:
'Chioma'+' '+'Onyeanula'

'Chioma Onyeanula'

In [12]:
a= 'My name is'+' '+ 'Chioma'


In [14]:
a[11:17]

'Chioma'

In [15]:
#adding the step indexation
y = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20


In [17]:
y[0:21:2]

(1, 3, 5, 7, 9, 11, 13, 15, 17, 19)

In [1]:
for i in "Mississippi":
    print(i)

M
i
s
s
i
s
s
i
p
p
i


In [2]:
for i in "Chioma":
    print(i)

C
h
i
o
m
a


In [10]:
x = [2,3,5,8]
for i in x:
    print(i ** 2)


4
9
25
64


In [17]:
print("life isn't fair")

life isn't fair


In [18]:
print('"stay hungry, stay foolish"')

"stay hungry, stay foolish"


In [28]:
print(' "keep going. You\'re getting there." ')

 "keep going. You're getting there." 


In [30]:
print('"you shouldn\'t put your eggs in one basket"')

"you shouldn't put your eggs in one basket"


In [31]:
string = 'Hello \nWorld'
print(string)

Hello 
World


In [40]:
Name = 'Chioma'
Age = 20
Gender = 'Female'

print(f'my name is {Name}, i am {Age} years old and i am {Gender} gender')

my name is Chioma, i am 20 years old and i am Female gender


In [43]:
Name = 'Chioma'
Age = 25
Attitude = 'cool'
print('hey {} you are {} years old and you are {}' .format(Name, Age, Attitude))

hey Chioma you are 25 years old and you are cool


In [44]:
print('it\'s "kinda" sunny outside')

it's "kinda" sunny outside


In [45]:
y = 4

if y % 2 ==0:
    print('even')
else:
    print('odd')

even


In [55]:
Age = int(input('your Age as a number'))


if Age >=17 and Age <=22:
    print('Gen Z')
elif Age >= 23 and Age <=30:
    print('younger Millennial')
elif Age >= 31 and Age <=38:
    print('older Millenial')
elif Age >=39 and Age <=54:
    print('X')lif Age >=55 and Age <=73:
    print('baby boomer')
else:
    print('Age not in my list')

your Age as a number 22


Gen Z


In [60]:
order_total = int(input('amount'))
customer_membership = bool(input('statement'))

if order_total >=100 and customer_membership == True:
    print('Discount applied.')
else:
    print('Discount not applied.')

amount 100
statement True


Discount applied.


In [61]:
order_total = int(input('amount'))
customer_location = input('location')

if order_total >=50 or customer_location == "USA":
    print('free shipping applied.')
else:
    print('shipping fee applied.')


amount 50
location USA


free shipping applied.


In [9]:
List = [17, 38, 10, 25, 72]


In [10]:
print(List)

[17, 38, 10, 25, 72]


In [11]:
List.sort()


In [12]:
print(List)

[10, 17, 25, 38, 72]


In [13]:
List.append(12)
print("After adding 12:", List)

After adding 12: [10, 17, 25, 38, 72, 12]


In [14]:
List.reverse()
print("Reversed list:", List)

Reversed list: [12, 72, 38, 25, 17, 10]


In [15]:
Name = 'Alice'
Age = 20

print(f'my name is {Name} and i am {Age} years old')

my name is Alice and i am 20 years old


In [18]:
item = "laptop"
price = 850.50

print(f'The price of {item} is {price}')

The price of laptop is 850.5


In [22]:
product = "phone"
quantity = 3
unit_price = 299.99

print(f'{quantity} * {product} @ {unit_price}') == 899.97


3 * phone @ 299.99


False

In [1]:
#continuation sequence
x = 5 + 7 + 8\
- 11 / 13\
* 12 - 3\
+ 5

In [3]:
#while loop
count = 1

while count <= 10:
    print(count)
    if count == 8:
        break
    count += 1

1
2
3
4
5
6
7
8


In [2]:
movie cost = 5
concert cost = 10

total cost = movie cost + concert cost
print(f" the total cost is: ${total cost}")

 the total cost is: $15


In [3]:
dict ={"name" : "Muanya", "age" : 1, "type" : "cool"}

dict.pop("age")

1

In [5]:
text = "Hello World"
print(text.upper())

HELLO WORLD


In [6]:
text = "Hello World"
print(text.capitalize())

Hello world


In [1]:
def area_circle(radius = 1):
    area = 3.142 * radius ** 2
    return area


In [2]:
area_circle()

3.142

In [3]:
class Student():
    def __init__(self, name, age, department):
        self.name = name
        self.age = age
        self.department = department

In [4]:
student = Student( 'chioma', 10, 'engineering')

In [5]:
student.department

'engineering'

In [6]:
#mealplan

class Mealplan():
    def __init__(self, protein, carbohydrate, vitamins):
        self.protein = protein
        self.carbohydrate = carbohydrate
        self.vitamins = vitamins

In [8]:
monday = Mealplan('chicken', 'rice', 'spinach')

In [9]:
tuesday = Mealplan('beef', 'yam', 'carrots')

In [11]:
tuesday.vitamins

'carrots'

In [ ]:
#create a class name african president that has 3 arguments = 1. name 2. country 3. region (e.g West, North etc)
#also add a class obect called continent which should be named africa and race called black 
#also add the quality of the president based on attitude

class african_president():
    continent = 'africa'
    race = 'black'
    
    def __init__(self, name, country, region):
        self.name = name
        self.country = country
        self.region = region
    def 

In [2]:
#create a 1 dimension numpy array that contains 10 numbers and add up the 3rd and 9th element

arr = ([2,4,6,8,10,12,14,5,7,9])

print(arr[2] + arr[8])

13


In [22]:
import numpy as np
arr4 = np.array([[[1,2,3], [0,5,8], [3,4,9]], [[1,2,3], [7,5,6], [3,2,8]]])

arr4

array([[[1, 2, 3],
        [0, 5, 8],
        [3, 4, 9]],

       [[1, 2, 3],
        [7, 5, 6],
        [3, 2, 8]]])

In [23]:
arr4[1,1]

array([7, 5, 6])

In [21]:
arr4[1,1, ::-1]

array([6, 5, 7])

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,7,13])
print(a+b)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
#Import the Numpy library.
#Ask the user to enter the number of students and the number of subjects.
#Create a Numpy array to store the marks of each student in each subject. The array should have the shape (number of students, number of subjects).
#Ask the user to enter the marks of each student in each subject.
#Calculate the total marks for each student using the sum() function of Numpy.
#Calculate the percentage for each student using the total marks and the formula: percentage = (total marks / (number of subjects * 100)) * 100
#Calculate the grade for each student using the percentage and the following grading system:
#90% or above: A+
#80% or above: A
#70% or above: B+
#60% or above: B
#50% or above: C
#below 50%: F
#Display the result for each student in a tabular format with columns for student name, total marks, percentage, and grade.


import numpy as np

# Input number of students and subjects
num_students = int(input("Enter the number of students: "))
num_subjects = int(input("Enter the number of subjects: "))

# List to store student names
student_names = []

# NumPy array to store marks
marks = np.zeros((num_students, num_subjects))

# Input student names and marks
for i in range(num_students):
    name = input(f"\nEnter name of student {i + 1}: ")
    student_names.append(name)
    
    for j in range(num_subjects):
        marks[i][j] = float(input(f"Enter marks for subject {j + 1}: "))

# Calculate total marks for each student
total_marks = np.sum(marks, axis=1)

# Calculate percentage
percentage = (total_marks / (num_subjects * 100)) * 100

# Function to calculate grade
def calculate_grade(p):
    if p >= 90:
        return "A+"
    elif p >= 80:
        return "A"
    elif p >= 70:
        return "B+"
    elif p >= 60:
        return "B"
    elif p >= 50:
        return "C"
    else:
        return "F"

# Calculate grades
grades = [calculate_grade(p) for p in percentage]

# Display results in tabular format
print("\nStudent Results")
print("-" * 50)
print(f"{'Name':<15}{'Total Marks':<15}{'Percentage':<10}{'Grade'}")
print("-" * 50)

for i in range(num_students):
    print(f"{student_names[i]:<15}{total_marks[i]:<15.2f}{percentage[i]:<10.2f}{grades[i]}")

print("-" * 50)


In [2]:
import numpy as np

In [5]:
a = np.array([2,4,6,8,10,12])

In [6]:
a.shape

(6,)

In [9]:
b = a.reshape(2,3)

In [10]:
print(b)

[[ 2  4  6]
 [ 8 10 12]]


In [11]:
b.T

array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

In [29]:
#create a 1D vector and reassign values in the second row and 3rd element.

a = np.array([2,4,6,8,10,12])
b = a.reshape(2,3)
print(b)

[[ 2  4  6]
 [ 8 10 12]]


In [30]:
b[1,2] = 11

In [31]:
print(b)

[[ 2  4  6]
 [ 8 10 11]]
